name: Flutter Build APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código
      - uses: actions/checkout@v4

      # 2. Instalar Java (necesario para compilar Android)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Instalar Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # o la versión estable que uses

      # 4. Instalar dependencias
      - name: Install dependencies
        run: flutter pub get

      # 5. Compilar APK en modo release
      - name: Build APK (release)
        run: flutter build apk --release

      # 6. Guardar el APK como artefacto descargable
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

          path: build/app/outputs/flutter-apk/*.apk
